# Generated by Django 4.1.3 on 2022-12-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_employee_hourly_pay_employee_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
