# Generated by Django 4.1.3 on 2023-01-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_attendance_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="daily_break_hours",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
