# Generated by Django 4.1.3 on 2023-01-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_employee_daily_break_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="break_hours",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
