# Generated by Django 4.1.3 on 2023-01-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_attendance_break_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="shift_start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
